# yamllint disable rule:line-length
# SPDX-FileNotice: ğŸ…­ğŸ„1.0 This file is dedicated to the public domain using the CC0 1.0 Universal Public Domain Dedication <https://creativecommons.org/publicdomain/zero/1.0/>.
# SPDX-FileContributor: Jason Yundt <swagfortress@gmail.com> (2021â€“2022)
# yamllint enable

# This file only contains hooks that are affected by this problem:
# <https://github.com/pre-commit/pre-commit/issues/2178#issuecomment-1002163763>
#
# Make sure that the URLs, revs and ids match .pre-commit-config.yaml

%YAML 1.2
---
repos:
    -
        repo: https://github.com/lovesegfault/beautysh
        rev: v6.2.1
        hooks:
            - id: beautysh
